package org.magnos.jayjax;

public enum JayjaxMessage
{
	ACTION_DOES_NOT_MAP_TO_FUNCTION,
	ACTION_NOT_AVAILABLE_IN_UNSECURE_MODE,
	PARSE_REQUEST_VALUES_ERROR,
	BUILD_FUNCTION_ARGUMENTS_ERROR,
	SERIALIZATION_ERROR,
	CONFIGURATION_PARSING_ERROR,
	CONTROLLER_INSTANTIATION_ERROR,
	FUNCTION_INVOCATION_ERROR,
	VALIDATION_ERROR,
	RESPONSE_WRITING_ERROR,
	LISTENER_ERROR,
	SECURE_FUNCTION_UNSECURE_CONNECTION,
	WRONG_METHOD_FOR_FUNCTION
}
